dist: trusty

# The main language that this repo uses - this enables Gradle support
language: java

# run in container
sudo: false

# Job matrix
matrix:
  include:
    - name: "Java 6 compatible"
      jdk: oraclejdk8
      env: TARGET_COMPATIBILITY=6
    - name: "Java 7 compatible"
      jdk: oraclejdk8
      env: TARGET_COMPATIBILITY=7
    - name: "Java 8 compatible"
      jdk: oraclejdk8
      env: TARGET_COMPATIBILITY=8
    - name: "Java 11 compatible"
      jdk: oraclejdk11
      env: TARGET_COMPATIBILITY=11

# Install the repository locally - this downloads dependencies, compiles the source code, and
# creates all artifacts
install: ./gradlew assemble

# Runs tests that check the implementation (unit tests)
script: ./gradlew check --info

# Runs code coverage when everything else was successful

after_success:
- |
  if [ "$TRAVIS_BRANCH" = "release/1.4" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$TARGET_COMPATIBILITY" = "8" ]; then
    export CI_NAME="travis-ci"
    export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
    export CI_BRANCH="$TRAVIS_BRANCH"
    ./gradlew jacocoTestReport coveralls
  else
    echo "Skipping coveralls [branch=$TRAVIS_BRANCH; pull_request=$TRAVIS_PULL_REQUEST; target_compat=$TARGET_COMPATIBILITY]"
  fi


# Creates a GitHub release and deploys artifacts to this release
deploy:
  #############################################################################
  # The provider that simplifies communication with GitHub
  - provider: releases
    # The GitHub API key is read from the environment (needs to be configured in Travis CI)
    api_key: $API_KEY

    # Conditions that all must be true to create a release in the first place
    on:
      # Only on correct repo
      repo: Dynatrace/openkit-java
      # Only if this commit has tags should a release be initiated
      tags: true

    # Metadata of this release
    #
    # The name of this release
    name: openkit-java $(git tag --contains HEAD)
    # This release should be flagged as pre-release
    prerelease: true

    # Files to be added to this release
    file:
    - build/libs/openkit*-java*.jar
    - build/distributions/openkit*-javadoc.zip
    # Enable wildcard operators in the file selector above
    file_glob: true

    # Prevent cleanup of build that would otherwise delete artifacts
    skip_cleanup: true

  #############################################################################
  # JFrog Bintray is handled via gradle
  - provider: script
    script: ./gradlew bintrayUpload
    # Prevent cleanup of build that would otherwise delete artifacts
    skip_cleanup: true

    on:
      # Only on correct repo
      repo: Dynatrace/openkit-java
      # Only if this commit has tags should a release be initiated
      tags: true
