language: java
install: ./gradlew assemble
script: ./gradlew check -i
deploy:
  provider: releases
  api_key:
    secure: $API_KEY_SECURE
  name: openkit-java $(git tag --contains HEAD)
  prerelease: true
  file_glob: true
  file:
  - build/libs/openkit-java-*.jar
  - build/distributions/openkit-java-*.zip
  skip_cleanup: true
  on:
    tags: true
