language: java
install: ./gradlew assemble
script: ./gradlew check -i
deploy:
  provider: releases
  file_glob: true
  file:
  - build/libs/openkit-java-*.jar
  - build/distributions/openkit-java-*.zip
  skip_cleanup: true
  on:
    tags: true
# remove before production
    branch: travis-ci
# end remove
  prerelease: true
