dist: trusty

# The main language that this repo uses - this enables Gradle support
language: java

# run in container
sudo: false

# Additional packages to install
addons:
  apt:
    packages:
      - openjdk-6-jdk
      - oracle-java8-installer

# Job matrix
matrix:
  include:
    - name: "Java 6 compatible"
      jdk: openjdk7 # start with OpenJDK7 and switch later to 6
      env:
        - INCLUDE_IN_COVERAGE=false
        - GRADLE_DIST_URL=https://services.gradle.org/distributions/gradle-3.5.1-bin.zip
        - SWITCH_TO_OPENJDK6=true
    - name: "Java 7 compatible"
      jdk: openjdk7
      env:
        - INCLUDE_IN_COVERAGE=false
        - GRADLE_DIST_URL=https://services.gradle.org/distributions/gradle-3.5.1-bin.zip
    - name: "Java 8 compatible"
      jdk: oraclejdk8
      env:
        - INCLUDE_IN_COVERAGE=true
    - name: "Java 11 compatible"
      jdk: oraclejdk11
      env:
        - INCLUDE_IN_COVERAGE=false
    - name: "Java 12 compatible"
      jdk: openjdk12
      env:
        - INCLUDE_IN_COVERAGE=false

install:
- |
  # next patch the gradle wrapper properties
  if [ "x$GRADLE_DIST_URL" != "x" ]; then
      GRADLE_WRAPPER_PROPERTIES=./gradle/wrapper/gradle-wrapper.properties
      echo "Patching $GRADLE_WRAPPER_PROPERTIES file using dist URL $GRADLE_DIST_URL"
      sed -i -e "s#distributionUrl=.*#distributionUrl=$GRADLE_DIST_URL#g" $GRADLE_WRAPPER_PROPERTIES
  fi
  # next assemble
  ./gradlew assemble

# Runs tests that check the implementation (unit tests)
script:
- |
  # run tests
  # check if switching to OpenJDK 6 is needed
  $JAVA_6_HOME=""
  if [ "$SWITCH_TO_OPENJDK6" = true ]; then
      JAVA_6_HOME=$(jdk_switcher home openjdk6)
      ./gradlew check -Ptest.executable=$JAVA_6_HOME --info
  else
      # no need to switch to Java 6
      ./gradlew check --info
  fi


# Runs code coverage when everything else was successful

after_success:
- |
  if [ "$TRAVIS_BRANCH" = "main" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$INCLUDE_IN_COVERAGE" = true ]; then
    export CI_NAME="travis-ci"
    export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
    export CI_BRANCH="$TRAVIS_BRANCH"
    ./gradlew jacocoTestReport coveralls
  else
    echo "Skipping coveralls [branch=$TRAVIS_BRANCH; pull_request=$TRAVIS_PULL_REQUEST; target_compat=$TARGET_COMPATIBILITY]"
  fi
